@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title initial state

class uniquePersonList as "<u>uniquePersonList:UniquePersonList</u>"
class student1 as "<u>student1:Person</u>" {}
class student2 as "<u>student2:Person</u>" {}
class studentName1 as "<u>studentName1:Name</u>" {
    name = "Alice"
}
class studentName2 as "<u>studentName1:Name</u>" {
    name = "Bob"
}
class studentId1 as "<u>studentId1:StudentId</u>" {
    studentId = "A0234567X"
}
class studentId2 as "<u>studentId2:StudentId</u>" {
    studentId = "A0345678X"
}
class studentEmail1 as "<u>studentEmail1:Email</u>" {
    email = "e0234567@u.nus.edu"
}
class studentEmail2 as "<u>studentEmail2:Email</u>" {
    email = "e0345678@u.nus.edu"
}
class studentGrade1 as "<u>studentGrade1:Grade</u>" {
    grade = "A"
}
class studentGrade2 as "<u>studentGrade2:Grade</u>" {
    grade = "B"
}
class studentGroup1 as "<u>studentGroup1:Group</u>" {
    group = "Group 1"
}
class studentGroup2 as "<u>studentGroup2:Group</u>" {
    group = "Group 2"
}
student1 -[hidden]right-> student2

uniquePersonList -down-> student1
uniquePersonList -down-> student2
student1 -down-> studentName1
student2 -down-> studentName2
student1 -down-> studentId1
student2 -down-> studentId2
student1 -down-> studentEmail1
student2 -down-> studentEmail2
student1 -down-> studentGrade1
student2 -down-> studentGrade2
student1 -down-> studentGroup1
student2 -down-> studentGroup2
@enduml
