@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Current state before modification

package addressBook <<rectangle>> {
    class State1 as "<u>p0:Person</u>" {
        studentId = A0123456X
    }
    class State2 as "<u>p1:Person</u>" {
        studentId = A1234567H
    }
}

State1 -[hidden]right-> State2
@enduml