@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "group gp/3 id/A0123456X id/A0000000H"

package States <<rectangle>> {
    class State1 as "<u>p0:Person</u>\nstudentId:A0123456X"
    class State2 as "<u>p1:Person</u>\nstudentId:A1234567H"
}

State1 -[hidden]right-> State2
@end
